#!/bin/bash
# Achievement System Testing Guide

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  ECHOMAZE 2.0 - ACHIEVEMENT SYSTEM v2 TESTING GUIDE           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎮 TO TEST ACHIEVEMENTS:"
echo ""
echo "1. Start the game locally (python3 -m http.server 8000 in game/ folder)"
echo "2. Open browser console (F12 or Ctrl+Shift+I)"
echo "3. Enable debug mode (press Ctrl+Shift+A in game)"
echo "4. Use test commands:"
echo ""
echo "   📋 LIST ALL ACHIEVEMENTS:"
echo "   → window.ACHIEVEMENT.list()"
echo ""
echo "   🔓 UNLOCK SPECIFIC ACHIEVEMENT:"
echo "   → window.ACHIEVEMENT.unlock('level1_clear')"
echo "   → window.ACHIEVEMENT.unlock('ending_good')"
echo "   → window.ACHIEVEMENT.unlock('ending_bad')"
echo ""
echo "   🎉 UNLOCK ALL ACHIEVEMENTS:"
echo "   → window.ACHIEVEMENT.unlockAll()"
echo ""
echo "   📊 CHECK PROGRESS:"
echo "   → window.ACHIEVEMENT.progress()"
echo "   Shows: { unlocked: X, total: 56, percentage: Y% }"
echo ""
echo "   🧹 CLEAR ALL (FOR FRESH TESTING):"
echo "   → window.ACHIEVEMENT.clear()"
echo ""
echo "   ❓ SHOW ALL COMMANDS:"
echo "   → window.ACHIEVEMENT.help()"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ KEY FEATURES TO TEST:"
echo ""
echo "  ✓ Notifications appear when achievement unlocks"
echo "  ✓ Notifications have correct tier colors"
echo "  ✓ Skins unlock automatically"
echo "  ✓ Sound plays on unlock (check audio.js)"
echo "  ✓ Debug mode persists after refresh"
echo "  ✓ Achievements persist in localStorage"
echo "  ✓ All three endings unlock correctly"
echo "  ✓ 100% achievement triggers at 56/56"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 ENDING TESTS:"
echo ""
echo "  NORMAL ENDING:"
echo "  → Play through Level 10, defeat boss"
echo "  → Don't enter Level 11"
echo "  → Should unlock 'ending_normal' ✓"
echo ""
echo "  GOOD ENDING:"
echo "  → Play through Level 10 & 11"
echo "  → When power prompt appears, click YES ✓ (green)"
echo "  → Should unlock 'ending_good' + 'guardian' skin ✓"
echo ""
echo "  BAD ENDING:"
echo "  → Play through Level 10 & 11"
echo "  → When power prompt appears, click NO ✗ (red)"
echo "  → Should unlock 'ending_bad' + 'shadow' skin ✓"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🐛 DEBUG TIPS:"
echo ""
echo "  • Check console for [ACHIEVEMENT] logs"
echo "  • Notifications should appear bottom-right"
echo "  • Mobile: Notifications scale responsively"
echo "  • Each tier has unique gradient color"
echo "  • Achievements survive page refresh"
echo "  • Debug mode survives page refresh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎨 TIER COLORS:"
echo ""
echo "  Bronze:   #CD7F32 (gold-brown)"
echo "  Silver:   #C0C0C0 (light gray)"
echo "  Gold:     #FFD700 (bright gold)"
echo "  Platinum: #E5E4E2 (pearl white)"
echo "  Diamond:  #00CED1 (cyan - RGB effects)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ NEW FEATURES:"
echo ""
echo "  ✨ Completely rebuilt achievement system"
echo "  ✨ Beautiful notification UI with animations"
echo "  ✨ Full debug/testing mode (Ctrl+Shift+A)"
echo "  ✨ All 56 achievements properly mapped"
echo "  ✨ Three ending achievements + skin unlocks"
echo "  ✨ Dev tools integrated and ready"
echo "  ✨ Responsive mobile design"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Ready to test! Open console and start unlocking achievements ║"
echo "╚════════════════════════════════════════════════════════════════╝"
