#!/bin/bash
# EchoMaze 2.0 - Comprehensive Achievement Verification Script
# This script verifies all achievements can be triggered correctly

echo "╔═══════════════════════════════════════════════════════════════════════╗"
echo "║    ECHOMAZE 2.0 - ACHIEVEMENT VERIFICATION & TESTING TOOL            ║"
echo "╚═══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 Total Achievements: 46"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 ACHIEVEMENT CATEGORIES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🥉 BRONZE (3 achievements):"
echo "   • level1_clear - Complete Level 1"
echo "   • first_death - Die for the first time"
echo "   • endless_wave_10 - Reach wave 10 in Endless"
echo ""
echo "🥈 SILVER (8 achievements):"
echo "   • level5_clear - Complete Level 5 [Unlocks: rookie skin]"
echo "   • speedrun_level_60s - Complete level in <60s [Unlocks: blitz skin]"
echo "   • no_abilities_level - Level without shield/jump"
echo "   • deathless_3_levels - 3 consecutive perfect levels"
echo "   • generator_perfect_3 - Perfect generator checks x3"
echo "   • boss_mount_3_pigs - Mount 3 pigs in boss fight"
echo "   • endless_wave_20 - Reach wave 20 in Endless"
echo "   • trap_master - Catch 25 enemies in traps"
echo ""
echo "🥇 GOLD (15 achievements):"
echo "   • level10_clear - Defeat the Core [Unlocks: veteran skin]"
echo "   • ending_good - Good Ending [Unlocks: guardian skin]"
echo "   • ending_bad - Bad Ending [Unlocks: shadow skin]"
echo "   • ending_normal - Normal Ending"
echo "   • perfect_shield_10 - Reflect 10 projectiles [Unlocks: defender skin]"
echo "   • speedrun_level3_30s - Level 3 in <30s"
echo "   • no_abilities_3_consecutive - 3 levels without abilities"
echo "   • generator_perfect_10 - Perfect checks x10 [Unlocks: technician skin]"
echo "   • boss_ammo_efficient - Defeat boss with ≤6 reloads"
echo "   • endless_wave_30 - Wave 30 [Unlocks: infinite skin]"
echo "   • endless_perfect_wave - Perfect wave (no damage)"
echo "   • endless_no_abilities_10 - 10 waves without abilities"
echo "   • secret_level11_power - Discover L11 power supply [Unlocks: glitch skin]"
echo "   • secret_code_alpha - Enter secret code [Unlocks: void skin]"
echo "   • bazooka_mode_unlock - Unlock Blaster Mode (SECRET)"
echo "   • glitch_teleport_escape - Dodge damage 5+ times"
echo ""
echo "💎 PLATINUM (8 achievements):"
echo "   • game_complete - Complete the game [Unlocks: engineer skin]"
echo "   • speedrun_game_20m - Game in <20 min [Unlocks: chrono skin]"
echo "   • deathless_game - Deathless run [Unlocks: ghost skin]"
echo "   • speedrun_game_10m - Game in <10 min [Unlocks: time_lord skin]"
echo "   • endless_wave_40 - Wave 40"
echo "   • endless_wave_50 - Wave 50"
echo "   • level11_unlock - Unlock Level 11 (SECRET)"
echo "   • total_deaths_100 - Die 100 times [Unlocks: phoenix skin] (SECRET)"
echo "   • bazooka_boss_victory - Defeat boss w/ Blaster"
echo "   • level10_survival_5min - Survive 5 min on L10"
echo "   • perfect_generator_run - Perfect all generators"
echo "   • shield_perfect_level - No damage + 10 reflects"
echo ""
echo "💠 DIAMOND (5 achievements):"
echo "   • why_destroy_power - Destroy power w/ bazooka (SECRET)"
echo "   • all_endings - Unlock all endings"
echo "   • endless_wave_60 - Wave 60"
echo "   • 100_percent - All achievements [Unlocks: hundred_percent skin] (RGB)"
echo "   • the_first_10 - Top 10 100% achievers (SECRET, RGB, CODE)"
echo "   • world_record - Verified speedrun record (SECRET, RGB)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 HOW TO TEST"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  START THE GAME"
echo "   Run in game/ folder:"
echo "   $ python3 -m http.server 8000"
echo "   Then open: http://localhost:8000"
echo ""
echo "2️⃣  ENABLE DEBUG MODE"
echo "   Press Ctrl+Shift+A in game (or F1 to open dev panel)"
echo "   Or run in console: window.ACHIEVEMENT.enableDebug()"
echo ""
echo "3️⃣  TEST COMMANDS"
echo ""
echo "   📊 VIEW ALL ACHIEVEMENTS:"
echo "   > window.ACHIEVEMENT.list()"
echo ""
echo "   🔓 UNLOCK SPECIFIC ACHIEVEMENT:"
echo "   > window.ACHIEVEMENT.unlock('level1_clear')"
echo "   > window.ACHIEVEMENT.unlock('ending_good')"
echo ""
echo "   🎉 UNLOCK ALL (TESTING ONLY):"
echo "   > window.ACHIEVEMENT.unlockAll()"
echo ""
echo "   📈 CHECK PROGRESS:"
echo "   > window.ACHIEVEMENT.progress()"
echo ""
echo "   🧹 CLEAR ALL:"
echo "   > window.ACHIEVEMENT.clear()"
echo ""
echo "   ℹ️  SHOW HELP:"
echo "   > window.ACHIEVEMENT.help()"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ KEY VERIFICATION TESTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "TEST 1: Level Completion Achievements"
echo "   • Play Level 1 → Should unlock 'level1_clear'"
echo "   • Play Level 5 → Should unlock 'level5_clear' + rookie skin"
echo "   • Beat Boss → Should unlock 'level10_clear' + veteran skin"
echo ""
echo "TEST 2: Ending Achievements"
echo "   • Good Ending → Unlock Level 11, press E, choose Yes, get note"
echo "   • Bad Ending → Unlock Level 11, press E, choose No"
echo "   • Normal Ending → Collect all 3 glitch orbs, beat Level 10"
echo "   • All Endings → Should auto-unlock 'all_endings'"
echo ""
echo "TEST 3: Speedrun Achievements"
echo "   • Any level <60s → 'speedrun_level_60s'"
echo "   • Level 3 <30s → 'speedrun_level3_30s'"
echo "   • Game <20min → 'speedrun_game_20m'"
echo "   • Game <10min → 'speedrun_game_10m'"
echo ""
echo "TEST 4: Challenge Achievements"
echo "   • No abilities (1 level) → 'no_abilities_level'"
echo "   • No abilities (3 levels) → 'no_abilities_3_consecutive'"
echo "   • Deathless (3 levels) → 'deathless_3_levels'"
echo "   • Deathless (full game) → 'deathless_game'"
echo ""
echo "TEST 5: Generator Achievements"
echo "   • Perfect x3 → 'generator_perfect_3'"
echo "   • Perfect x10 → 'generator_perfect_10' + technician skin"
echo "   • Perfect all → 'perfect_generator_run'"
echo ""
echo "TEST 6: Shield Achievements"
echo "   • 10 reflects → 'perfect_shield_10' + defender skin"
echo "   • No damage + 10 reflects → 'shield_perfect_level'"
echo ""
echo "TEST 7: Boss Achievements"
echo "   • Mount 3 pigs → 'boss_mount_3_pigs'"
echo "   • ≤6 reloads → 'boss_ammo_efficient'"
echo "   • Survive 5 min → 'level10_survival_5min'"
echo "   • Defeat w/ Blaster → 'bazooka_boss_victory'"
echo ""
echo "TEST 8: Endless Mode Achievements"
echo "   • Wave 10 → 'endless_wave_10'"
echo "   • Wave 20 → 'endless_wave_20'"
echo "   • Wave 30 → 'endless_wave_30' + infinite skin"
echo "   • Wave 40 → 'endless_wave_40'"
echo "   • Wave 50 → 'endless_wave_50'"
echo "   • Wave 60 → 'endless_wave_60'"
echo "   • Perfect wave → 'endless_perfect_wave'"
echo "   • 10 waves no abilities → 'endless_no_abilities_10'"
echo ""
echo "TEST 9: Secret Achievements"
echo "   • Unlock Level 11 → 'level11_unlock'"
echo "   • Find power supply → 'secret_level11_power' + glitch skin"
echo "   • Enter secret code → 'secret_code_alpha' + void skin"
echo "   • Unlock Blaster → 'bazooka_mode_unlock'"
echo "   • Destroy power w/ Blaster → 'why_destroy_power'"
echo "   • 100 deaths → 'total_deaths_100' + phoenix skin"
echo ""
echo "TEST 10: Special Achievements"
echo "   • All achievements → '100_percent' + hundred_percent skin"
echo "   • Verified record → 'world_record' (admin only)"
echo "   • Top 10 → 'the_first_10' (code limited)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 COMMON ISSUES & FIXES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ Achievement doesn't unlock:"
echo "   1. Check console for errors (F12)"
echo "   2. Enable debug mode: Ctrl+Shift+A"
echo "   3. Verify event is firing: Check dev panel logs"
echo "   4. Try manually: window.ACHIEVEMENT.unlock('achievement_id')"
echo ""
echo "❌ Notification doesn't show:"
echo "   1. Check ui-notifications.js is loaded"
echo "   2. Verify showAchievementUnlocked() exists"
echo "   3. Check CSS for notification styling"
echo ""
echo "❌ Skin doesn't unlock:"
echo "   1. Check skins.js is loaded"
echo "   2. Verify unlockSkin() function exists"
echo "   3. Check achievement has unlockSkin property"
echo "   4. Try: window.SKINS.unlock('skin_name')"
echo ""
echo "❌ Sound doesn't play:"
echo "   1. Check audio.js is loaded"
echo "   2. Verify playAchievementUnlock() exists"
echo "   3. Check audio is not muted"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 SKIN UNLOCKS (17 Total)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  rookie - Level 5"
echo "  blitz - Speedrun <60s"
echo "  veteran - Beat boss"
echo "  guardian - Good ending"
echo "  shadow - Bad ending"
echo "  defender - 10 reflects"
echo "  technician - Perfect x10"
echo "  infinite - Wave 30"
echo "  glitch - L11 power supply"
echo "  void - Secret code"
echo "  engineer - Complete game"
echo "  chrono - Speedrun <20min"
echo "  ghost - Deathless run"
echo "  time_lord - Speedrun <10min"
echo "  phoenix - 100 deaths"
echo "  hundred_percent - 100%"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Ready to test! Good luck! 🎮"
echo ""
